version: '3.9'

services:
  rsnapshot:
    container_name: rsnapshot
    image: lscr.io/linuxserver/rsnapshot:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuching
    volumes:
      - /data/rsnapshot/config:/config
      - /data/rsnapshot/snapshots:/.snapshots #optional
      - /data/rsnapshot/data:/data #optional
    restart: unless-stopped